### ISSUE TITLE
ブラウザからインターネットショートカット(.URL)をD&Dしたときにちゃんと動作しない

### ISSUE THREAD

**Issue by orz-** [Saccubus/Saccubus1.x#1]
ブラウザ(firefox)からURL先頭のアイコンを管理タブにD&Dしたとき
URLに変換されず　ショートカットファイル.URL(tempフォルダのパス)がURL/ID欄に入力される
ver 1.62.1.2
環境: Windows10 64bit　Java8 1.8.0_74
ソース: frontend

**Comment by orz-** [comment]
修正終わり　2.28

**Comment by orz-** [comment]
修正終わり　2.28

**Comment by ledyba** [comment]
For Your Information: Close and commentを押すと、修正が終わったバグをCloseしてIssueリストから除外できますよ（消されるわけではないので後からも見れます）

**Comment by orz-** [comment]
なるほど　
修正終わったのでclose
