### ISSUE TITLE
変換中のスリープ防止機能、変換後にシャットダウン機能

### ISSUE THREAD

**Issue by orz-** [Saccubus/Saccubus1.x#53]
http://potato.2ch.net/test/read.cgi/software/1449586179/522
変換中のスリープ防止機能、変換後にシャットダウン機能もあれば便利だけど
なきゃないで現状に不満はない最高のツールです作者感謝

**Comment by ShaneWilton** [comment]
❤️ 💚 💙 💛 💜

**Comment by orz-** [comment]
変換中のスリープ防止は多分難しい
変換後にシャットダウンもGUIの操作が一定時間なかったらと言う感じにする？
自分としてはPCが時間で電源切れるのが嫌い（スクリーンセイバーも嫌い）なので気が進まない
とりあえず保留して　暫くしたらclose予定

**Comment by orz-** [comment]
とりあえず close

**Comment by orz-** [comment]
シャットダウンじゃなくて
変換が終わったら一定時間後にプログラム終了ならいいかなと思うので
検討に戻す。

**Comment by orz-** [comment]
commit c5009ff5eae8f2bd4c5d959934f88f88c9dcbca6
でさきゅばす終了機能を追加。
このissueはこの件で一旦close　
シャットダウン機能は再度要望があれば再検討

**Comment by orz-** [comment]
commit 0acd7c2d09dbbf24b747c12d91697e3893e106c0 で再修正
