### ISSUE TITLE
ffmpegをプロセス優先度lowで起動する

### ISSUE THREAD

**Issue by orz-** [Saccubus/Saccubus1.x#57]
http://potato.2ch.net/test/read.cgi/software/1449586179/539

> 重いプロセス（ffmpeg？）は全てプロセス優先度lowで起動してほしいです

**Comment by orz-** [comment]
出来ない。
JavaにはWindows用の優先度を変更するインターフェースがない。
cmd.exeとstartを使うとffmpegの入出力パイプが切れてしまい起動即終了する。
何か方法を思いつくまでreject
close

**Comment by orz-** [comment]
追記　ffmpegの使うスレッドを -thread 0 から -thread 1　に変えれば多少は軽くなるだろうけど
そもそもプロセスの優先度変えたって体感的な重い軽いは変わらないから
なぜ低優先度起動したいかがわからない。

**Comment by ledyba** [comment]
一応プロセスが起動した後にプライオリティを変える方法はあるみたいです（Linuxのreniceのような感じ）
http://reich.exblog.jp/21002580/
http://www.atmarkit.co.jp/ait/articles/0804/18/news154.html

ただlowにしたところで体感では変わらないよな〜とわたしも思います

**Comment by orz-** [comment]
どもありがとうございます。
前にもプライオリティ変えたいって言う話は有ったんですけど
「エンコードが始まると重いから」という理由ならthreadsを減らすほうが
確実に軽くなるはずなんですよねえ。確実に遅くもなると思いますが。
今シングルコアCPU使ってる人も居ないでしょうし（？）

**Comment by orz-** [comment]
起動した後でプロセスを見つけて優先度変更する機能を
さきゅばすに組み込むんじゃなくて、こういうのを使ったらいいんじゃないかな
http://www.gigafree.net/security/process/ApplicationPriorityChanger.html
Windows!0で使ってみた感じ優先度はソフトの監視間隔で（起動後ほぼすぐに）
優先度変更されてるみたい。
（ffmpegプロセス自体は別だけどexe名で監視してるから大丈夫）
優先度変更したらその時ブラウザが軽くなるかは実際にそういう状況じゃないと
わからないと思うけど

![aplicationpriority](https://cloud.githubusercontent.com/assets/3416733/24318761/21bdcbda-114e-11e7-9b99-0670f866ba8b.png)

起動時に低優先に指定できるならやるんだけど（今は方法不明）
起動した後でプロセス見つけて優先度変更ってのは気が乗らないｗ

**Comment by orz-** [comment]
なにか条件・状況が変わらないならしばらくしたらcloseする。

**Comment by orz-** [comment]
採用せず　close
